<a href="https://colab.research.google.com/github/seidumohammed/DataCamp/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
array = np.array(range(5))

In [6]:
array

array([0, 1, 2, 3, 4])

In [8]:
array_2d = np.array([range(5), range(5)])
array_2d

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [9]:
array.shape

(5,)

In [10]:
array_2d.shape

(2, 5)

In [12]:
array.size

5

In [13]:
array_2d.T

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [14]:
array_2d.T.shape

(5, 2)

In [15]:
array.ndim

1

In [16]:
array_2d.ndim

2